### ISSUE TITLE
ユーザーログインの流れを作る

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#10]
ログイン時の流れ、軽く作ってしまいましょう。

1. ユーザーサインアップのためのメールアドレス、パスワード入力
2. ユーザー情報を入力する

上記を経ると、ログイントップへ画面遷移

**Comment by jonakp** [comment]
@ms2sato 
Issue#10に関して、PRを出しました。
ご確認ください。
https://github.com/jonakp/macro_share_v2/pull/11#issue-228156054
