### ISSUE TITLE
ユーザ情報から推奨カロリー等のデータ計算＆結果の表示

### ISSUE THREAD

**Issue by jonakp** [jonakp/macro_share_v2#12]
以下２点を実施します。
1. 登録したユーザ情報から、推奨カロリー、プロテイン、脂質、炭水化物を算出するロジックを実装する¥
2. 算出結果をユーザー画面に表示。

**Comment by ms2sato** [comment]
@jonakp 承知しました！都合の良いタイミングで実施して大丈夫です！
