### ISSUE TITLE
【調査】【時間のある時に】scopeについて調査する

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#14]
このプロジェクトでも導入していく機能なので、ActiveRecordのscopeについて調べましょう。どういうものか理解できれば大丈夫です！調べたURLや理解できたことをこのIssueにコメントしてください。

**Comment by jonakp** [comment]
@ms2sato 
# ActiveRecordのscopeについて
## 概要
- 一言で言うと、"共通的に使うクエリをモデルのメソッドのように定義できる機能"。
- 複雑なSQLを何度も書かなくてよくなり、可読性と保守性を向上させることができる。
- Active Record Query Interfaceを使う箇所(whereなど)は、
  基本scopeを使っていく位に考えても良さそう。
  - 複数回同じクエリを出す場合は特に
## 使い方
```
class Article < ApplicationRecord
  scope :published, -> { where(published: true) }
end
```

`Article.published # => [published articles]
`
## その他気になったポイント
- scopeでのメソッドの設定は、クラスメソッドの定義と完全に同じ
```
# "使い方"で記載したscopeと下記のクラスメソッド定義は等価
class Article < ApplicationRecord
  def self.published
    where(published: true)
  end
end
```
- scope同士をチェインさせられる＆scope内で別scope をチェインさせるられる
```
class Article < ApplicationRecord
  scope :published,               -> { where(published: true) }
  scope :published_and_commented, -> { published.where("comments_count > 0") }
end
```
- 引数や条件文も使える(が扱いには多少注意が必要そう)
- default scopeを使うと、全てのscopeに共通のscopeを設定できる

## 疑問点
https://railsguides.jp/active_record_querying.html#%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97
の”スコープをスコープ内でチェイン (chain) ”と”14.4 スコープのマージ”は、
やっている事は変わらないという認識であっているでしょうか？

## 参考サイト
https://ruby-rails.hatenadiary.com/entry/20140814/1407994568
https://railsguides.jp/active_record_querying.html#%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97

**Comment by ms2sato** [comment]
@jonakp 概ね理解大丈夫です！疑問点についてお答えします。

```rb
User.active.merge(User.inactive)
```

こちらはあまり例がよくないですね。マージの良いところは別のテーブルの内容を持ってこれることです。例えばUserとUserfetureが繋がっている場合、以下のようなことができます。JOINのような他のテーブルと結合した場合に有効ということです！

```rb
User.joins(:user_feature).active.merge(UserFeature.current)
```

**Comment by ms2sato** [comment]
OKそうなので一旦Close。気になったら引き続きこちらにコメントくださーい

**Comment by jonakp** [comment]
@ms2sato 
コメントありがとうございます！

> こちらはあまり例がよくないですね。マージの良いところは別のテーブルの内容を持ってこれることです。例えばUserとUserfetureが繋がっている場合、以下のようなことができます。JOINのような他のテーブルと結合した場合に有効ということです！
> 
> User.joins(:user_feature).active.merge(UserFeature.current)

mergeを使うと、RelationのあるModelのscopeも使える、と理解しました！
(調べているなかで、改めてSQL勉強しないと、、、と感じました；)

認識に誤りがありましたら、ご指摘ください。

**Comment by ms2sato** [comment]
@jonakp 理解問題ないです！

SQLについては、例えば上記のようなActiveRecordのコードを一度書いてみると、RailsがログとしてSQLを出し手くれるので、その内容を調べてみるなどすると通常と逆順ですが学習はしやすいですよ。
