### ISSUE TITLE
【調査】【時間のある時に】enumについて調べる

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#15]
Railsのenumについて調べましょう。調べたURLや理解できたことをこのIssueにコメントしてください。
シンプルな割に機能が豊富ですよ。

**Comment by jonakp** [comment]
@ms2sato 
調査結果以下に記載します。
ご確認お願いします！

# Railsのenumについて
## 概要
- modelでenumを使う事で、状態を表すattributeを任意の識別子を用いて扱えるようになる
(マジックナンバーを使わなくて済む)
- formでselectタグと組み合わせて利用する
- macro-shareにおいては、性別(gender)・活動量(activity)・目的(purpose)などで用いる方針

##  使い方
- 配列やハッシュで宣言できる。(ハッシュの場合は、値も指定できる)
```
class Conversation < ActiveRecord::Base
  enum status: [ :active, :archived ]
end
``` 
`
enum status: { active: 0, archived: 1 , else: 9}
`
- DB的にはintegerでも、rails上ではsymbolを使って操作ができる。
```
# conversation.update! status: 0
conversation.active!
conversation.active? # => true
conversation.status  # => "active"
```
- 普通にquery用のinterfaceを使ってもOK
`Conversation.where(status: [:active, :archived])
`

- prefix/suffixも使える
```
class Conversation < ActiveRecord::Base
  enum status: [:active, :archived], _suffix: true
  enum comments_status: [:active, :inactive], _prefix: :comments
end
```
```
conversation.active_status!
conversation.archived_status? # => false

conversation.comments_inactive!
conversation.comments_active? # => false
```

## 注意事項
- enumを使う場合は、columnにデフォルト値を入れた方が良さそう
```
create_table :conversations do |t|
  t.column :status, :integer, default: 0
end
```

## 参考ページ
https://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html
https://morizyun.github.io/ruby/rails-function-enum-select-tag.html
https://framgia.com/journal/railsのenum-諸刃の剣（１）-%E3%80%80from-viblo/

**Comment by ms2sato** [comment]
下記の記法が一般的です！

```rb
enum status: { active: 0, archived: 1 , else: 9}
```
