### ISSUE TITLE
【調査】例外について調査する

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#18]
プログラミングで「例外」という機能を使ってエラーを処理することがあります。これがどういうものか調べてこのIssueに結果をまとめてください。参考にしたURLを貼ったり、自分の言葉で説明をするなどして欲しいです。

**Comment by jonakp** [comment]
※作成中。。。
## 例外
- エラーが起きてプログラムの実行を続けることができなくなった状態
-  rubyではraiseメソッドによって発生する
   - rubyなりrailsなりgemなりの中で元々定義されている
   - もしくは自分で定義する
## 例外処理
- 発生した例外を捕捉して処理すること
- 例外処理を明示的に書くことで、例外が発生してもプログラムを続行させることが可能
  - 例外が発生した際、何もしなければプログラムは強制終了する
    - 例外発生以降の処理は実施されない
- rubyではbegin-rescue-end構文を使う

## 例外処理の使い所
- どういった時に例外処理を使うのが適切か、が重要
- 安易にrescueしない
  - 例えばrailsなら例外発生時の共通処理が存在するので、基本はそちらに任せる
- どういう時使うのが適切か？

- 例外発生時

- 例外
  - 
- 例外処理


## メモ
- raiseで例外を発生させることは、「例外処理」に含まれるのでしょうか？
  - 「例外処理」= 「発生した例外を捕捉して処理する事」を表しており、
例外を発生させること自体は、「例外処理」に含まれないのか？と感じました。
- rubyにおける例外は、誰かがどこかでraiseを使って定義している、という認識で合っていますでしょうか？

- 全ての例外は、いずれかの場所でraiseされている事による？

- イマイチ使い所が分からない。
  - コーディングミスも含めたら内部のエラーなんてどこで起きるか分からない
  - 外部の機能と連携している箇所、に関しては納得できる。
- 

## 参考サイト
https://speakerdeck.com/jnchito/number-rubykansai-2018-01-13?slide=45

**Comment by ms2sato** [comment]
@jonakp こちら一旦対面で確認終えていると認識してます。もしも違ってたら指摘ください！

**Comment by jonakp** [comment]
@ms2sato 
はい。対面で教えていただいた認識です。
Closeする形でよろしいでしょうか？

**Comment by ms2sato** [comment]
終わっているんですねー。Closeします！
