### ISSUE TITLE
【Bug】userfeatureから性別のみ変えた際に、推奨カロリー等が再計算されない

### ISSUE THREAD

**Issue by jonakp** [jonakp/macro_share_v2#20]
@ms2sato 
ちょっとしたBugを見つけました。
影響さほど大きく無い＆少し面倒くさそう なので、後回しにしようかと思っています。
こういった内容はIssueの形で残しておいてよろしいでしょうか？

このトレーニングではこうするのが望ましい、等ありましたら教えてください。

[内容]
特定のuserfeatureをUpdateする際、性別のみ変更しても、推奨カロリーが更新されない。

性別がuser管理である事から、
userfeature modelのbefore_validationに設定されたculculate_calorie_macroが、
性別のみの変更だと実行されないのではないかと予想

[期待動作]
性別のみの更新でも、推奨カロリー等が更新されること。

**Comment by ms2sato** [comment]
@jonakp Issue化しておいて大丈夫です。手があいた時にやっていいですよ。
