### ISSUE TITLE
Scaffoldする

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#3]
- Userfeature
- FoodHistory

についてScaffoldします。

**Comment by ms2sato** [comment]
> リソースの間のリレーション

これはやってしまいましょう！Issueの質問はIssue上でやっていきましょう。そうすればIssueを見るだけでどのような経緯で決定に至ったかもわかります。仕様の確認などは特にこちらでやります。

**Comment by ms2sato** [comment]
@jonakp 
> リソースの間のリレーション

これはやってしまいましょう！
また、Issueの質問はIssue上でやっていきましょう。そうすればIssueを見るだけでどのような経緯で決定に至ったかもわかります。仕様の確認などは特にこちらでやります。

**Comment by jonakp** [comment]
@ms2sato 
2件質問させてください。
### 質問１
Userfeature&Foodhistory のuser_idカラムに関して、
外部キー制約は付けるほうが望ましいでしょうか？
（付けない場合は、belongs_to :user, optional: true の形をとろうかなぁと思っています）

参考にしたサイト：
https://qiita.com/iguchi1124/items/218e35a145f372062ea4

### 質問2
外部キーをつける場合、
user_id(外部キー)の型は、integerとreferenceのどちらが良いでしょうか？

参考にしたサイト：
https://qiita.com/ryouzi/items/2682e7e8a86fd2b1ae47

### 質問の背景
以下3点実行した所、
> ActiveRecord::RecordInvalid (Validation failed: Users must exist)
というエラーが出てきました。

1. 
> bin/rails g scaffold userfeature user_id:integer height:integer weight:integer age:integer activity:integer purpose:integer total_calorie:integer protein:integer fat:integer carbo:integer
2.
> class Userfeature < ApplicationRecord
>   belongs_to :user
> end
(&user側でhas_many追加)
3.
> user = User.first
> user.userfeatures.create!()

調べた結果外部キー関連の対応が必要そう？と考えていますが、
対応方針が複数あり、どれがいいかなぁと判断つかない状況です。

**Comment by jonakp** [comment]
一つ前の質問：補足
user_idに外部キーを付ける＆型をreferenceにする、
方針がいいかな？と個人的には感じています。

**Comment by ms2sato** [comment]
@jonakp 質問ありがとうございます！

## 作法的なこと
動かしてみて動かない、コードを書いたらxxx、的な状況の時には、PullRequestを作って質問すると良いですよ。その際`[WIP]` とタイトルにつけると「まだ作業中です」と伝えることができます。今回の状況も私はソース全体を見せてもらった方が早いのでそうして欲しいです。

## 内容について
### 質問1
外部キー制約は付けるべきです。基本的に外部キー制約は付けられるところには付けましょう。DB内のデータが予想外になる（例えばNULLになっていけないものがNULLになる）などは後で困ることが多いので、制約できることは制約します。同じようにunique制約などもできる限りつけます。

今回、Userfeatureの中で、user_idがNULLになるのは明らかにおかしなデータだから、必ずつけましょう。

### 質問2
`references` ですね。Railsのバージョンによって外部キー制約の型が変わったりするので、`references`での統一が最も良いと思います。実際に出来上がったカラムを見るとわかりますが、適切な数値型にRailsが勝手に合わせて作ってくれますよ。

### 質問3
確かにちゃんと動きそうな操作をしているので、ソースコード見たいです！PullRequest作ってくだされー。

**Comment by jonakp** [comment]
@ms2sato
仕事終わったら直ぐにpull request出します！
あと今後は込み入った話はコードベースで議論できるように、wipを積極的に使うようにしますね。

今回のwipの流れは以下の感じでしょうか？
1. とりあえずエラーが出て来た状況のソースで専用にブランチを切ってpull request。commit messageとpull requestのコメントに[wip]を付ける
2. レビューいただいている裏で、私は外部キー関連の実装を進める。
3. レビュー指摘がある場合は取り入れつつ、実装が終わったら同じブランチで再度pull request

参考にしたサイト:
https://qiita.com/numa08/items/b676e38e3dbabfd39d18

**Comment by ms2sato** [comment]
@jonakp WIPはとても良いのでぜひ慣れてください。

基本的にブランチはIssue（タスク）ごとに立てるので、今回だとこのIssueに対応したPull Request（PRと略します）を作ります。その上で現在のエラー状況などをコメントしてください。

流れとしては良さそうなのでこの順序で大丈夫です。今は @jonakp さんが一人で1ブランチを見ているだけなので、私がコメントしたことを同じブランチで実装していけば大きな混乱はないと思います。

ではPRお願いします。

**Comment by jonakp** [comment]
@ms2sato 
まずエラーが起きる状況のコードをPRしました。ご確認ください。
https://github.com/jonakp/macro_share_v2/pull/8#issue-227278223

引き続き外部キー制約の実装の上、再度PRする予定です。

**Comment by jonakp** [comment]
@ms2sato 
外部キー制約実装し、再度Pushしました。
ご確認ください。
https://github.com/jonakp/macro_share_v2/pull/8#issuecomment-434707870

**Comment by jonakp** [comment]
@ms2sato 
マージしました。OKでしたらIssueもCloseお願いします。(でいいんです？)
