### ISSUE TITLE
[手が空いたら]いいね！機能のモデルのテストを書く

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#30]

**Comment by jonakp** [comment]
以下の方針で作成

- とりあえず１個作ってみる
- exampleの構成を検討
- factory bot でテストデータを作る
- 検討したexampleに沿って作り込む

**Comment by jonakp** [comment]
対面の結果、以下の方針で進めます。
- いいね機能実装に関連して各モデルに追加したメソッドをテストする
  - モデルのSpecに対しては、メソッドのテストが最優先
  - 複雑なscope, custom validationがあればそれらも対象となる
- Factory Botを用いて、いい感じのコードにする
