### ISSUE TITLE
foodhistoryに複数の画像を追加する

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#32]
画像を複数追加できるようにしたいので、ちょっと設計変更が必要かとー

**Comment by jonakp** [comment]
@ms2sato 
CarrierWaveを使おうと考えていますが、OKでしょうか？
複数画像追加の機能も標準で持っている認識です。

https://github.com/carrierwaveuploader/carrierwave
https://qiita.com/ggtmtmgg/items/ba5f275c122c83013ea1

対面で相談させてください。

**Comment by jonakp** [comment]
対面で相談の結果を踏まえ、以下の形で進めるようにします。

- CarrierWaveを利用する。
  - ただし、CarrierWaveの複数画像追加機能は利用しない
    - https://qiita.com/ggtmtmgg/items/ba5f275c122c83013ea1
- まず画像アップロードだけのプロジェクトを作ってみて、
1つの画像をCarrierWaveでアップロードする機能を試す
- そのあとMacroShareに戻って、複数画像アップロード機能を追加していく
  - 画像用のテーブルを作成して、foodhistoryと１対多のassociationを作成する。
