### ISSUE TITLE
「いいね」したら通知が飛ぶ

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#33]
「いいね」した際の動きを以下のようにする。

- Likeの新規保存
- いいねされたFoodHistoryの所有者へメール送信
- いいねされた通知の情報（モデル、テーブルは考えてください）をDBへ保存
  - この情報の一覧画面を作成（通知一覧のようなもの）

![img_3976](https://user-images.githubusercontent.com/627817/49683174-a8c8b680-fb03-11e8-84db-b5a9bd5d955b.JPG)

**Comment by ms2sato** [comment]
@jonakp 
Notificationですが、
- user_id 
  - 通知を表示するユーザーのID
- like_id
  - 今回作成されたLike

で良いと思いますよ。今回の通知はあくまで Likeされたことを知らせたいです。Likeが取れれば誰がLikeしたかと、LikeされたFoodHistoryも取れますから。

**Comment by jonakp** [comment]
ありがとうございます！

> Likeが取れれば誰がLikeしたかと、LikeされたFoodHistoryも取れますから。

そうでした。。。Likeだけあれば、
私が定義したfrom_user_idもliked_foodhistory_idも取れてしいますね；
(associationを活かす発想がまだ弱い様です；もう少し意識していきます)

ER図を修正しました。
この形で進めようと思います。
![database](https://user-images.githubusercontent.com/41995085/49898499-8edcfa00-fe9c-11e8-9968-35f31acf7f90.png)

**Comment by ms2sato** [comment]
@jonakp ER図承知です。線は引いてない様子ですがカラム名からすいさツッしました。大丈夫でしょう。like_idはreferenceですね。

**Comment by jonakp** [comment]
@ms2sato 
> ER図承知です。線は引いてない様子ですがカラム名から推察しました。大丈夫でしょう。like_idはreferenceですね。

すみません。大丈夫ではありませんでした。。。
LikeとNotificationの間にassociationを作成するつもりはありませんでした；

このassociationは、１対１という認識で合っていますでしょうか？

association作成した方が、明らかに実装が楽だ、という点は感じました。
ただ、当然association作成するよね？という所までは自分の認識として行き着けていません。
この辺り別途対面で相談させてください。
