### ISSUE TITLE
画像アップロードを適切にする

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#36]
学習のために以下の変更をやりましょう。

- [ ] Foodhistory にバリデーションを仕掛ける（例えばnameは必須にするなどしてバリデーションエラーが発生するようにします）
- [ ] バリデーションエラーが発生した際にも、画像が保持されるようにする（上記のバリデーションを仕掛けると、バリデーションエラー直後にアップロードした画像が消えてしまうはずです。それを回避します）
- [ ] 画像の削除はチェックボックスにチェックを行うことでやりましょう。

この内容ですが、最初なかなか苦労するところなのと、`accept_nested_attributes_for` `carrierwave`についての理解が必要です。ただ、一度やっておけばコツがわかると思うので取り組んでみて欲しいです。

参考に、シンプルにまとめたサンプルプロジェクトを示しておきます。一度これを動かしてみると色々とわかると思います。
https://github.com/CircleAround/rails_idioms-multiple_images_by_carrierwave/

**Comment by jonakp** [comment]
PRにcloseを付け忘れました。
マージまで実施したので、closeします。
