### ISSUE TITLE
Likeをソフトデリート（論理削除）する

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#37]
論理削除して、Notificationが消えてしまわないようにしましょう。

**Comment by jonakp** [comment]
@ms2sato 
１件質問させてください。
rails 論理削除で調べて見た所、以下gemを見つけました。
https://github.com/jhawthorn/discard#why-not-paranoia-or-acts_as_paranoid

こちらを利用する形でよろしいでしょうか？
もしくは本トレーニングとしては、
上記使わない方が良いでしょうか？

なお、使わない場合は以下の方針で進めようと考えています。
# 実装方針
- likes テーブルに"deleted" column(Boolean型)を追加
  - default/null: falseを指定する
- like/unlikeの処理を以下の形で変更
  - unlike時は対応するrecordのdeletedを trueに変更する
  - like時は
     - 対応するrecordがあれば、deletedを trueに変更する
     - 対応するrecordがなければ、createする
- foodhistory index, like/unlikeの表示条件を、deletedを考慮した形に変更する
  - likes.where(user: user).present?(liked_byメソッド)のwhere条件を修正する
