### ISSUE TITLE
ログインしたユーザーがUserfeature を作成した時に、アソシエーションされるようにする。

### ISSUE THREAD

**Issue by ms2sato** [jonakp/macro_share_v2#6]
Deviseについて調査すると、ある方法で「現在ログインしているユーザーの情報」を取得することができます（ユーザーのIDやemailアドレスなど、Userモデルの内容が取れます）。

この情報をUserfeatureを作成する際に利用するように直します。

- Userfeatureの作成や変更のフォームで user_id を入力できないように項目を消す。・
- UserfeatureをDBに作成する際に、user_idが「現在ログインしているユーザーのID」になるように修正する
- （努力目標）画面のヘッダ部分などにリンクをつけて、Userfeatureの一覧画面へ入れるようにする。

**Comment by jonakp** [comment]
@ms2sato 
修正の上、PRを行いました。ご確認ください。
https://github.com/jonakp/macro_share_v2/pull/9#issue-227770361
